import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Roboto} from 'next/font/google';


const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100' , '300' , '400' , '500' , '700' , '900'],
  style: ['normal' , 'italic'],
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Landing Page",
  description: "Generated by Somesh Tripathi",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className={roboto.className} >
        {children}
      </body>
    </html>
  );
}
